# Generated by Django 5.2.10 on 2026-06-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent de terrain'), ('ADMIN', 'Administrateur'), ('AUDITEUR', 'Auditeur'), ('COMPTABLE', 'Comptable')], default='CLIENT', max_length=20),
        ),
    ]
