# Generated by Django 6.0.6 on 2026-06-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_jours', models.IntegerField()),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Produit d'assurance",
                'verbose_name_plural': "Produits d'assurance",
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20)),
                ('date_souscription', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='accounts.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.insuranceproduct')),
            ],
            options={
                'verbose_name': "Police d'assurance",
                'verbose_name_plural': "Polices d'assurance",
            },
        ),
    ]
