# Generated by Django 6.0.6 on 2026-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['client', 'statut'], name='insurance_p_client__e88247_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['date_fin', 'statut'], name='insurance_p_date_fi_a50f2a_idx'),
        ),
    ]
