# Generated by Django 6.0.6 on 2026-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0003_amortizationschedule_loans_amort_loan_id_9f46f4_idx_and_more'),
        ('repayments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan', 'date_paiement'], name='repayments__loan_id_a5a798_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['agent', 'date_paiement'], name='repayments__agent_i_e9832d_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['reference'], name='repayments__referen_662802_idx'),
        ),
    ]
