# Generated by Django 6.0.6 on 2026-06-10 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0004_loanproduct_collateral_graceperiod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('PRODUIT', 'Produit'), ('CHARGE', 'Charge')], max_length=10, verbose_name='Type')),
                ('niveau', models.IntegerField(default=1, verbose_name='Niveau')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde actuel')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='accounting.account', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque'), ('DIVERS', 'Opérations diverses'), ('OD', 'OD'), ('ASSURANCE', 'Assurance')], max_length=20, verbose_name='Journal')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('date_ecriture', models.DateField(verbose_name="Date d'écriture")),
                ('libelle', models.TextField(verbose_name='Libellé')),
                ('est_validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='accounts.agent', verbose_name='Agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='accounts.client', verbose_name='Client')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='loans.loanapplication', verbose_name='Prêt')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_entries', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date_ecriture', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=10, verbose_name='Sens')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant')),
                ('libelle', models.TextField(blank=True, verbose_name='Libellé')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='accounting.account', verbose_name='Compte')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Écriture')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['entry', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_c93a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type'], name='accounting__type_01d50f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent'], name='accounting__parent__da6035_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference'], name='accounting__referen_3e7084_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date_ecriture'], name='accounting__date_ec_0bea3a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['journal', 'date_ecriture'], name='accounting__journal_87cc15_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['est_validee'], name='accounting__est_val_33b363_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['entry'], name='accounting__entry_i_27304d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='accounting__account_6fdc67_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['entry', 'account'], name='accounting__entry_i_ce00ce_idx'),
        ),
    ]
