# Generated by Django 6.0.6 on 2026-06-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0004_loanproduct_collateral_graceperiod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidarityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SHG', 'Self-Help Group'), ('JLG', 'Joint Liability Group')], max_length=3)),
                ('centre', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('DISSOUS', 'Dissous')], default='ACTIF', max_length=8)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='accounts.agent')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_responsible', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Groupe Solidaire',
                'verbose_name_plural': 'Groupes Solidaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHEF', 'Chef'), ('MEMBRE', 'Membre'), ('SECRETAIRE', 'Secrétaire')], default='MEMBRE', max_length=10)),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solidarity_groups', to='accounts.client')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.solidaritygroup')),
            ],
            options={
                'verbose_name': 'Membre du Groupe',
                'verbose_name_plural': 'Membres du Groupe',
                'ordering': ['groupe', 'role'],
            },
        ),
        migrations.CreateModel(
            name='GroupeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_caution', models.CharField(choices=[('SOLIDAIRE', 'Solidaire'), ('INDIVIDUELLE', 'Individuelle')], default='SOLIDAIRE', max_length=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_loan', to='loans.loanapplication')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='groups.solidaritygroup')),
            ],
            options={
                'verbose_name': 'Prêt de Groupe',
                'verbose_name_plural': 'Prêts de Groupe',
                'ordering': ['groupe', 'loan'],
            },
        ),
        migrations.AddIndex(
            model_name='solidaritygroup',
            index=models.Index(fields=['type'], name='groups_soli_type_309dea_idx'),
        ),
        migrations.AddIndex(
            model_name='solidaritygroup',
            index=models.Index(fields=['statut'], name='groups_soli_statut_a872d3_idx'),
        ),
        migrations.AddIndex(
            model_name='solidaritygroup',
            index=models.Index(fields=['region'], name='groups_soli_region_e5e29f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['groupe', 'client'], name='groups_grou_groupe__d1c021_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['est_actif'], name='groups_grou_est_act_ef0592_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('groupe', 'client'), name='unique_group_member'),
        ),
        migrations.AddIndex(
            model_name='groupeloan',
            index=models.Index(fields=['groupe', 'loan'], name='groups_grou_groupe__43f97e_idx'),
        ),
        migrations.AddIndex(
            model_name='groupeloan',
            index=models.Index(fields=['type_caution'], name='groups_grou_type_ca_2bd020_idx'),
        ),
    ]
