# Generated by Django 6.0.6 on 2026-06-10 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0004_loanproduct_collateral_graceperiod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrudentialRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('formule', models.TextField(help_text='Description du calcul', verbose_name='Formule')),
                ('seuil_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Seuil minimum')),
                ('valeur_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valeur actuelle')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('statut', models.CharField(choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('EN_SURVEILLANCE', 'En surveillance')], default='EN_SURVEILLANCE', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Ratio prudentiel',
                'verbose_name_plural': 'Ratios prudentiels',
                'indexes': [models.Index(fields=['code'], name='compliance__code_8ed1ac_idx'), models.Index(fields=['statut'], name='compliance__statut_3fa17a_idx'), models.Index(fields=['date_calcul'], name='compliance__date_ca_cb1849_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeclarationSuspicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=100, verbose_name='Transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('motifs', models.TextField(verbose_name='Motifs')),
                ('date_faits', models.DateField(verbose_name='Date des faits')),
                ('date_declaration', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Référence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client', verbose_name='Client')),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
            ],
            options={
                'verbose_name': 'Déclaration de soupçon',
                'verbose_name_plural': 'Déclarations de soupçon',
                'indexes': [models.Index(fields=['client'], name='compliance__client__225284_idx'), models.Index(fields=['date_faits'], name='compliance__date_fa_f1e286_idx'), models.Index(fields=['date_declaration'], name='compliance__date_de_a7fc1b_idx'), models.Index(fields=['reference'], name='compliance__referen_4ab206_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoanClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('SAINE', 'Saine'), ('SOUS_SURVEILLANCE', 'Sous surveillance'), ('DOUTEUSE', 'Douteuse'), ('COMPROMISE', 'Compromise')], max_length=30, verbose_name='Classe')),
                ('jours_retard', models.IntegerField(default=0, verbose_name='Jours de retard')),
                ('taux_provision', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de provision')),
                ('montant_provision', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant de la provision')),
                ('date_classification', models.DateField(auto_now_add=True, verbose_name='Date de classification')),
                ('date_mise_a_jour', models.DateField(auto_now=True, verbose_name='Date de mise à jour')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication', verbose_name='Prêt')),
            ],
            options={
                'verbose_name': 'Classification de créance',
                'verbose_name_plural': 'Classifications de créances',
                'indexes': [models.Index(fields=['classe'], name='compliance__classe_83eb20_idx'), models.Index(fields=['jours_retard'], name='compliance__jours_r_464a15_idx'), models.Index(fields=['date_classification'], name='compliance__date_cl_8a0d0e_idx'), models.Index(fields=['date_mise_a_jour'], name='compliance__date_mi_18b109_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=20, verbose_name='Type')),
                ('periode', models.CharField(help_text='YYYY-MM for monthly, YYYY-T for quarterly, YYYY for annual', max_length=7, verbose_name='Période')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('FINALISE', 'Finalisé'), ('TRANSMIS', 'Transmis')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('contenu', models.JSONField(verbose_name='Contenu')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport réglementaire',
                'verbose_name_plural': 'Rapports réglementaires',
                'indexes': [models.Index(fields=['type', 'periode'], name='compliance__type_c8feb1_idx'), models.Index(fields=['statut'], name='compliance__statut_422774_idx'), models.Index(fields=['date_generation'], name='compliance__date_ge_6c5ba3_idx')],
                'unique_together': {('type', 'periode')},
            },
        ),
    ]
