# Generated by Django 6.0.6 on 2026-06-10 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('api_url', models.URLField()),
                ('api_key', models.TextField(help_text='Chiffrer au repos (AES-256-GCM)')),
                ('api_secret', models.TextField(help_text='Chiffrer au repos (AES-256-GCM)')),
                ('frais_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('frais_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Passerelle de paiement',
                'verbose_name_plural': 'Passerelles de paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_interne', models.CharField(max_length=100, unique=True)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('INITIE', 'INITIÉ'), ('EN_COURS', 'EN COURS'), ('SUCCES', 'SUCCÈS'), ('ECHEC', 'ÉCHEC'), ('REMBOURSE', 'REMBOURSÉ')], db_index=True, default='INITIE', max_length=20)),
                ('type', models.CharField(choices=[('VERSEMENT_EPARGNE', 'Versement épargne'), ('REMBOURSEMENT_CREDIT', 'Remboursement crédit'), ('DECAISSEMENT', 'Décaissement')], max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MTN_MOMO', 'MTN MoMo')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('est_verifie', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Compte Mobile Money',
                'verbose_name_plural': 'Comptes Mobile Money',
            },
        ),
    ]
