# Generated by Django 6.0.6 on 2026-06-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0004_loanproduct_collateral_graceperiod_and_more'),
        ('payments', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='savings.savingsaccount'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentgatewayconfig'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='loans.loanapplication'),
        ),
        migrations.AddConstraint(
            model_name='mobilemoneyaccount',
            constraint=models.UniqueConstraint(fields=('client', 'operateur', 'telephone'), name='uq_client_operateur_telephone'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['statut', 'reference_interne'], name='payments_pa_statut_5ba4e2_idx'),
        ),
    ]
