# Generated by Django 6.0.6 on 2026-06-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('taux_interet_annuel', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'intérêt annuel (%)")),
                ('duree_jours', models.IntegerField(blank=True, help_text='Laissez vide pour une durée illimitée', null=True, verbose_name='Durée (jours)')),
                ('montant_min', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant minimum')),
                ('montant_max', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant maximum')),
                ('type', models.CharField(choices=[('DAV', 'Dépôt à Vue'), ('DAT', 'Dépôt à Terme'), ('EPARGNE', 'Épargne Programmée'), ('LOGEMENT', 'Épargne Logement')], max_length=10, verbose_name='Type de produit')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Produit d'épargne",
                'verbose_name_plural': "Produits d'épargne",
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['type'], name='savings_sav_type_558f01_idx'), models.Index(fields=['est_actif'], name='savings_sav_est_act_fe9d99_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20, unique=True, verbose_name='Numéro de compte')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CLOTURE', 'Clôturé'), ('BLOQUE', 'Bloqué')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_epargne', to='accounts.client', verbose_name='Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='savings.savingsproduct', verbose_name="Produit d'épargne")),
            ],
            options={
                'verbose_name': "Compte d'épargne",
                'verbose_name_plural': "Comptes d'épargne",
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VERSEMENT', 'Versement'), ('RETRAIT', 'Retrait'), ('INTERET_CREDITEUR', 'Intérêt créditeur'), ('FRAIS', 'Frais')], max_length=20, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Solde avant')),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Solde après')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_epargne', to='accounts.agent', verbose_name='Agent')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsaccount', verbose_name='Compte')),
            ],
            options={
                'verbose_name': "Transaction d'épargne",
                'verbose_name_plural': "Transactions d'épargne",
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['statut'], name='savings_sav_statut_d0d4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['client', 'statut'], name='savings_sav_client__0ee39a_idx'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['type'], name='savings_sav_type_8d3826_idx'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['compte', 'date_transaction'], name='savings_sav_compte__7bdf76_idx'),
        ),
    ]
