# Generated by Django 6.0.6 on 2026-06-09 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'status'], name='support_cha_client__9902d1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agent', 'status'], name='support_cha_agent_i_63a635_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['date_mise_a_jour'], name='support_cha_date_mi_81a449_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='support_cha_convers_565b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='support_cha_convers_f73fae_idx'),
        ),
    ]
