# Generated by Django 6.0.6 on 2026-06-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.IntegerField()),
                ('motif', models.TextField()),
                ('revenu_mensuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('score_eligibilite', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('DECAISSEE', 'Décaissée')], default='SOUMISE', max_length=20)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysed_loans', to='accounts.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PIECE_IDENTITE', "Pièce d'identité"), ('JUSTIFICATIF_REVENU', 'Justificatif de revenu'), ('PHOTO_CLIENT', 'Photo du client')], max_length=30)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensualite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('capital_restant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('part_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('part_interet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_paye', models.BooleanField(default=False)),
                ('numero_mensualite', models.IntegerField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedule', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['date_echeance'],
            },
        ),
    ]
