# Generated by Django 6.0.6 on 2026-06-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='loans.loanapplication', verbose_name='Prêt')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-date'],
            },
        ),
    ]
