# Generated by Django 6.0.6 on 2026-06-09 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0002_loanstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='amortizationschedule',
            index=models.Index(fields=['loan', 'est_paye'], name='loans_amort_loan_id_9f46f4_idx'),
        ),
        migrations.AddIndex(
            model_name='amortizationschedule',
            index=models.Index(fields=['date_echeance', 'est_paye'], name='loans_amort_date_ec_60046b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['loan', 'type'], name='loans_docum_loan_id_9bc9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['client', 'statut'], name='loans_loana_client__57bbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['agent', 'statut'], name='loans_loana_agent_i_a808e1_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['date_creation'], name='loans_loana_date_cr_a4c81b_idx'),
        ),
        migrations.AddIndex(
            model_name='loanstatushistory',
            index=models.Index(fields=['loan', 'date'], name='loans_loans_loan_id_9a26e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='amortizationschedule',
            constraint=models.UniqueConstraint(fields=('loan', 'numero_mensualite'), name='unique_loan_numero_mensualite'),
        ),
    ]
