# Generated by Django 6.0.6 on 2026-06-10 11:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0003_amortizationschedule_loans_amort_loan_id_9f46f4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type_pret', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('PROFESSIONNEL', 'Professionnel'), ('EQUIPEMENT', 'Équipement'), ('AGRICOLE', 'Agricole'), ('GROUPE', 'Groupe'), ('SAISONNIER', 'Saisonnier')], default='PERSONNEL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('taux_interet_annuel', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('montant_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duree_min_mois', models.IntegerField(default=1)),
                ('duree_max_mois', models.IntegerField(default=60)),
                ('frequence_remboursement', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('TRIMESTRIEL', 'Trimestriel')], default='MENSUEL', max_length=20)),
                ('taux_penalite_jour', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=5)),
                ('garantie_requise', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit de crédit',
                'verbose_name_plural': 'Produits de crédit',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BIEN_IMMOBILIER', 'Bien immobilier'), ('VEHICULE', 'Véhicule'), ('CAUTION_SOLIDAIRE', 'Caution solidaire'), ('DEPOT_GARANTIE', 'Dépôt de garantie'), ('MATERIEL', 'Matériel'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('valeur_estimee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fichier_justificatif', models.FileField(blank=True, null=True, upload_to='collaterals/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('caution_solidaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garanties_donnees', to='accounts.client')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Garantie',
                'verbose_name_plural': 'Garanties',
            },
        ),
        migrations.CreateModel(
            name='GracePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_debut', models.IntegerField(help_text='Numéro de mensualité de début')),
                ('mois_fin', models.IntegerField(help_text='Numéro de mensualité de fin')),
                ('type_interet', models.CharField(choices=[('CAPITALISE', 'Capitalisé'), ('PAYE', 'Payé')], default='CAPITALISE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_periods', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Période de grâce',
                'verbose_name_plural': 'Périodes de grâce',
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='loans.loanproduct', verbose_name='Produit de crédit'),
        ),
        migrations.CreateModel(
            name='LoanRestructuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REECHELONNEMENT', 'Rééchelonnement'), ('REFINANCEMENT', 'Refinancement'), ('REPORT_ECHEANCE', "Report d'échéance"), ('REDUCTION_TAUX', 'Réduction de taux')], max_length=20)),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=20)),
                ('nouvelle_duree_mois', models.IntegerField(blank=True, null=True)),
                ('nouveau_taux', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nouveau_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('motif', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restructurings_approved', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restructurings', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Restructuration de prêt',
                'verbose_name_plural': 'Restructurations de prêt',
            },
        ),
    ]
