# Generated by Django 5.2.10 on 2026-06-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanproduct_collateral_graceperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='statut',
            field=models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('DECAISSEE', 'Décaissée'), ('REMBOURSEE', 'Remboursée')], default='SOUMISE', max_length=20),
        ),
    ]
