# Generated by Django 5.2.10 on 2026-06-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_is_active_alter_user_role'),
        ('loans', '0005_alter_loanapplication_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['is_active'], name='loans_loana_is_acti_32fe74_idx'),
        ),
    ]
