# Generated by Django 6.0.6 on 2026-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanapplication_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='commission_agent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission agent en pourcentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='frais_dossier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de frais de dossier', max_digits=5),
        ),
    ]
